Tabs->spaces

diff --git a/scripts/qc-dump b/scripts/qc-dump
--- a/scripts/qc-dump
+++ b/scripts/qc-dump
@@ -2,29 +2,29 @@
 
 dir="$1"
 if [ -z "$dir" ]; then
-	echo "Usage: $0 directory"
-	exit 0
+    echo "Usage: $0 directory"
+    exit 0
 fi
 
 if [ ! -d "$dir" ]; then
-	echo "Directory does not exist!"
-	exit 1
+    echo "Directory does not exist!"
+    exit 1
 fi
 
 errors=""
 function flag {
-	msg="$@"
-	errors=`cat <<ERR
+    msg="$@"
+    errors=`cat <<ERR
 $errors$msg
 ERR
 `
 }
 
 function assert_file {
-	f="$1"
-	if [ ! -e "$f" ]; then
-		flag "Required file $f is missing!"
-	fi	
+    f="$1"
+    if [ ! -e "$f" ]; then
+        flag "Required file $f is missing!"
+    fi  
 }
 
 cd $dir
@@ -34,8 +34,8 @@ assert_file metadata.tbl
 assert_file features.tab
 assert_file functions.tab
 if [ -n "$errors" ]; then
-	echo "$errors"
-	exit 0
+    echo "$errors"
+    exit 0
 fi
 
 proteins=.proteins.$$
@@ -44,24 +44,24 @@ featctgs=.featctgs.$$
 cds=.cds.$$
 grep '^>' proteins.fa | cut -c2- | sort > $proteins
 if [ -n "$(grep " " $proteins)" ]; then
-	flag "[proteins.fa] Spaces found in IDs"
+    flag "[proteins.fa] Spaces found in IDs"
 fi
 grep '^>' contigs.fa | cut -c2- | sort > $contigs
 if [ -n "$(grep " " $contigs)" ]; then
-	flag "[contigs.fa] Spaces found in IDs"
+    flag "[contigs.fa] Spaces found in IDs"
 fi
 (cut -f3 | tr ',' '\n' | sed 's/_[^_]*$//' | sort -u) < features.tab > $featctgs
 missctgs=$(join -v1 $featctgs $contigs)
 if [ -n "$missctgs" ]; then
-	cat <<EOF > missing-feature-contigs.txt
+    cat <<EOF > missing-feature-contigs.txt
 $missctgs
 EOF
-	flag "[features.tab] Referenced contigs missing from contigs.fa (missing-feature-contigs.txt)"
+    flag "[features.tab] Referenced contigs missing from contigs.fa (missing-feature-contigs.txt)"
 fi
 (awk '$2=="CDS"' | cut -f1 | sort) < features.tab > $cds
 missproteins=$(join -v1 $cds $proteins)
 if [ -n "$missproteins" ]; then
-	cat <<EOF > missing-proteins.txt
+    cat <<EOF > missing-proteins.txt
 $cds
 EOF
     flag "[proteins.fa] CDS IDs in features.tab missing from proteins (missing-proteins.txt)"
@@ -72,6 +72,6 @@ rm $featctgs
 rm $cds
 
 if [ -n "$errors" ]; then
-	echo "$errors"
-	exit 0
+    echo "$errors"
+    exit 0
 fi
